### ISSUE TITLE
No use of the fillMode Image property

### ISSUE THREAD

**Issue by nedo99** [bramharimukti/PelagicoreMusicPlayer#6]
Since on of the requirements is to fit the UI size based on the image size, one should not use the fillMode (Image.Strech or for instance) since those properties are used when we want to change the image size.

Images should have their original size. You can leave them for the album covers since those images should be scaled.

**Comment by bramharimukti** [comment]
Fill Mode for the album cover has been removed.

SHA : ed985d8a8774dbb7679cff0aa4f91bf8458302d6
