### ISSUE TITLE
Create Tool component for images with action (play, forward, shuffle, etc)

### ISSUE THREAD

**Issue by nedo99** [bramharimukti/PelagicoreMusicPlayer#7]
Since in the code there are multiple images with action (play, pause, etc), which means that you have duplicated code. What would be better approach is to create separate component called lets say Tool and which will have required properties. Then in the code, instead of using Image and MouseArea components every time you would write something like:
Tool {
     source: "play.png"
     onClicked: doSomething()
}

**Comment by bramharimukti** [comment]
Tool component required for the music player controller has been created and used in MusicController.qml.

SHA : ed985d8a8774dbb7679cff0aa4f91bf8458302d6
